import {
  Product,
  Order,
  Notification,
  UserProfile,
  SupplierEntry,
  Delivery,
  CategoryEntry,
  RegionEntry,
  AdminStats,
  UserEntry,
  ReportEntry,
  SupplierProduct,
  GroupOrderDetail,
  SavedOrderDraft,
} from "./types";

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: { en: "Premium Mixed Cheese Platter", ar: "طبق جبن مشكل فاخر" },
    description: {
      en: "A carefully curated selection of aged cheddar, gouda, brie, and local Arabic cheeses perfect for wholesale distribution.",
      ar: "مجموعة منتقاة بعناية من الشيدر القديم وجودا والبري والأجبان العربية المحلية المثالية للتوزيع بالجملة.",
    },
    price: 180.0,
    imageUrl:
      "https://images.unsplash.com/photo-1552767059-ce1833656d5b?auto=format&fit=crop&q=80&w=800",
    category: { en: "Dairy", ar: "ألبان" },
    stock: 200,
  },
  {
    id: "p2",
    name: { en: "Arabic Coffee - Premium Blend", ar: "قهوة عربية - مزيج فاخر" },
    description: {
      en: "Premium Arabic coffee blend made from high-quality Arabica beans with a hint of cardamom and saffron.",
      ar: "مزيج قهوة عربية فاخر مصنوع من حبوب أرابيكا عالية الجودة مع لمسة من الهيل والزعفران.",
    },
    price: 85.0,
    imageUrl:
      "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&q=80&w=800",
    category: { en: "Beverages", ar: "مشروبات" },
    stock: 350,
  },
  {
    id: "p3",
    name: {
      en: "Fresh Full Cream Milk (1L)",
      ar: "حليب طازج كامل الدسم (1 لتر)",
    },
    description: {
      en: "Fresh, pasteurized full cream milk sourced from local dairy farms. Ideal for cafes, restaurants, and food services.",
      ar: "حليب طازج مبستر كامل الدسم من مزارع ألبان محلية. مثالي للمقاهي والمطاعم وخدمات الطعام.",
    },
    price: 7.5,
    imageUrl:
      "https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&q=80&w=800",
    category: { en: "Dairy", ar: "ألبان" },
    stock: 1500,
  },
  {
    id: "p4",
    name: {
      en: "Extra Virgin Olive Oil (5L)",
      ar: "زيت زيتون بكر ممتاز (5 لتر)",
    },
    description: {
      en: "Cold-pressed extra virgin olive oil from Mediterranean olive groves. Rich flavor, perfect for cooking and dressing.",
      ar: "زيت زيتون بكر ممتاز معصور على البارد من بساتين الزيتون المتوسطية. نكهة غنية مثالية للطهي والتتبيل.",
    },
    price: 145.0,
    imageUrl:
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=800",
    category: { en: "Oils", ar: "زيوت" },
    stock: 80,
  },
  {
    id: "p5",
    name: { en: "Premium Medjool Dates (5kg)", ar: "تمر مجهول فاخر (5 كجم)" },
    description: {
      en: "Large, soft, and naturally sweet Medjool dates. Premium quality, hand-picked and sorted for wholesale.",
      ar: "تمر مجهول كبير وناعم وحلو طبيعياً. جودة فاخرة منتقاة يدوياً ومصنفة للبيع بالجملة.",
    },
    price: 220.0,
    imageUrl:
      "https://cdn.alweb.com/thumbs/allaboutdates/article/fit727x484/%D9%83%D9%84-%D9%85%D8%A7-%D9%8A%D9%87%D9%85%D9%83-%D9%85%D8%B9%D8%B1%D9%81%D8%AA%D9%87-%D8%B9%D9%86-%D8%AA%D9%85%D8%B1-%D9%85%D8%AC%D9%87%D9%88%D9%84.jpg",
    category: { en: "Dried Fruits", ar: "فواكه مجففة" },
    stock: 60,
  },
  {
    id: "p6",
    name: { en: "Pure Natural Honey (3kg)", ar: "عسل طبيعي نقي (3 كجم)" },
    description: {
      en: "100% pure, raw natural honey sourced from mountain apiaries. Rich in antioxidants and naturally antibacterial.",
      ar: "عسل طبيعي خام نقي 100% من مناحل جبلية. غني بمضادات الأكسدة ومضاد للبكتيريا طبيعياً.",
    },
    price: 195.0,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3f3rcfTrT2s6vt0p85PAgcGswAb9yidxsfQ&s",
    category: { en: "Honey", ar: "عسل" },
    stock: 40,
  },
  {
    id: "p7",
    name: { en: "Premium Basmati Rice (25kg)", ar: "أرز بسمتي فاخر (25 كجم)" },
    description: {
      en: "Extra-long grain premium Basmati rice with a distinctive aroma and fluffy texture. Sourced from the finest paddies.",
      ar: "أرز بسمتي فاخر طويل الحبة برائحة مميزة وقوام هش. من أفضل حقول الأرز.",
    },
    price: 165.0,
    imageUrl:
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800",
    category: { en: "Grains", ar: "حبوب" },
    stock: 300,
  },
  {
    id: "p8",
    name: {
      en: "Natural Mineral Water (1.5L x 12)",
      ar: "مياه معدنية طبيعية (1.5 لتر × 12)",
    },
    description: {
      en: "Pure natural mineral water sourced from underground springs. Packed in 12-bottle cases for bulk supply.",
      ar: "مياه معدنية طبيعية نقية من ينابيع جوفية. معبأة في صناديق من 12 زجاجة للتوريد بالجملة.",
    },
    price: 24.0,
    imageUrl:
      "https://images.unsplash.com/photo-1560023907-5f339617ea1b?auto=format&fit=crop&q=80&w=800",
    category: { en: "Beverages", ar: "مشروبات" },
    stock: 800,
  },
];

export const mockOrders: Order[] = [
  {
    id: "o1",
    orderNumber: "ORD-2024-001",
    items: [
      {
        productId: "p1",
        productName: {
          en: "Premium Mixed Cheese Platter",
          ar: "طبق جبن مشكل فاخر",
        },
        quantity: 20,
        unitPrice: 180,
        totalPrice: 3600,
      },
      {
        productId: "p3",
        productName: {
          en: "Fresh Full Cream Milk (1L)",
          ar: "حليب طازج كامل الدسم (1 لتر)",
        },
        quantity: 100,
        unitPrice: 7.5,
        totalPrice: 750,
      },
    ],
    totalAmount: 4350,
    status: "delivered",
    createdAt: "2024-10-15",
    estimatedDelivery: "2024-11-01",
    paymentMethod: "Bank Transfer",
    shippingAddress: { en: "King Fahd Road, Riyadh", ar: "طريق الملك فهد، الرياض" },
    trackingNumber: "SEL-987654",
  },
  {
    id: "o2",
    orderNumber: "ORD-2024-002",
    items: [
      {
        productId: "p5",
        productName: {
          en: "Premium Medjool Dates (5kg)",
          ar: "تمر مجهول فاخر (5 كجم)",
        },
        quantity: 30,
        unitPrice: 220,
        totalPrice: 6600,
      },
      {
        productId: "p6",
        productName: {
          en: "Pure Natural Honey (3kg)",
          ar: "عسل طبيعي نقي (3 كجم)",
        },
        quantity: 15,
        unitPrice: 195,
        totalPrice: 2925,
      },
    ],
    totalAmount: 9525,
    status: "shipped",
    createdAt: "2024-11-20",
    estimatedDelivery: "2024-12-05",
    paymentMethod: "Credit Card",
    shippingAddress: { en: "Industrial Zone, Dammam", ar: "المنطقة الصناعية، الدمام" },
    trackingNumber: "GFS-456123",
  },
  {
    id: "o3",
    orderNumber: "ORD-2024-003",
    items: [
      {
        productId: "p2",
        productName: {
          en: "Arabic Coffee - Premium Blend",
          ar: "قهوة عربية - مزيج فاخر",
        },
        quantity: 50,
        unitPrice: 85,
        totalPrice: 4250,
      },
      {
        productId: "p7",
        productName: {
          en: "Premium Basmati Rice (25kg)",
          ar: "أرز بسمتي فاخر (25 كجم)",
        },
        quantity: 10,
        unitPrice: 165,
        totalPrice: 1650,
      },
    ],
    totalAmount: 5900,
    status: "confirmed",
    createdAt: "2024-12-01",
    estimatedDelivery: "2024-12-20",
    paymentMethod: "Bank Transfer",
    shippingAddress: { en: "King Fahd Road, Riyadh", ar: "طريق الملك فهد، الرياض" },
  },
  {
    id: "o4",
    orderNumber: "ORD-2024-004",
    items: [
      {
        productId: "p4",
        productName: {
          en: "Extra Virgin Olive Oil (5L)",
          ar: "زيت زيتون بكر ممتاز (5 لتر)",
        },
        quantity: 25,
        unitPrice: 145,
        totalPrice: 3625,
      },
    ],
    totalAmount: 3625,
    status: "pending",
    createdAt: "2024-12-10",
    estimatedDelivery: "2024-12-28",
    paymentMethod: "Credit Card",
    shippingAddress: { en: "King Fahd Road, Riyadh", ar: "طريق الملك فهد، الرياض" },
  },
  {
    id: "o5",
    orderNumber: "ORD-2024-005",
    items: [
      {
        productId: "p8",
        productName: {
          en: "Natural Mineral Water (1.5L x 12)",
          ar: "مياه معدنية طبيعية (1.5 لتر × 12)",
        },
        quantity: 200,
        unitPrice: 24,
        totalPrice: 4800,
      },
    ],
    totalAmount: 4800,
    status: "cancelled",
    createdAt: "2024-11-05",
    estimatedDelivery: "2024-12-15",
    paymentMethod: "Bank Transfer",
    shippingAddress: { en: "Business Bay, Dubai", ar: "الخليج التجاري، دبي" },
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    title: { en: "Order Confirmed", ar: "تم تأكيد الطلب" },
    message: {
      en: "Your order ORD-2024-003 has been confirmed and is being prepared.",
      ar: "تم تأكيد طلبك ORD-2024-003 وهو قيد التحضير.",
    },
    type: "order",
    read: false,
    createdAt: "2024-12-01T10:30:00",
  },
  {
    id: "n2",
    title: { en: "Shipment Update", ar: "تحديث الشحنة" },
    message: {
      en: "Order ORD-2024-002 has been shipped and is on its way.",
      ar: "تم شحن الطلب ORD-2024-002 وهو في طريقه إليك.",
    },
    type: "order",
    read: false,
    createdAt: "2024-11-25T14:00:00",
  },
  {
    id: "n3",
    title: { en: "Order Delivered", ar: "تم توصيل الطلب" },
    message: {
      en: "Your order ORD-2024-001 has been delivered successfully.",
      ar: "تم توصيل طلبك ORD-2024-001 بنجاح.",
    },
    type: "order",
    read: true,
    createdAt: "2024-11-02T09:15:00",
  },
  {
    id: "n4",
    title: { en: "New Message from Supplier", ar: "رسالة جديدة من المورد" },
    message: {
      en: "Al-Madina Dairy Co. has sent you a message regarding your recent order.",
      ar: "أرسلت شركة ألبان المدينة رسالة بخصوص طلبك الأخير.",
    },
    type: "message",
    read: false,
    createdAt: "2024-12-02T16:45:00",
  },
  {
    id: "n5",
    title: { en: "System Update", ar: "تحديث النظام" },
    message: {
      en: "New features are now available. Check out the updated dashboard.",
      ar: "ميزات جديدة متاحة الآن. تفقد لوحة التحكم المحدثة.",
    },
    type: "system",
    read: true,
    createdAt: "2024-11-28T08:00:00",
  },
  {
    id: "n6",
    title: { en: "Price Drop Alert", ar: "تنبيه انخفاض السعر" },
    message: {
      en: "Premium Arabic Coffee has dropped in price by 8%.",
      ar: "انخفض سعر القهوة العربية الفاخرة بنسبة 8%.",
    },
    type: "system",
    read: false,
    createdAt: "2024-12-03T07:30:00",
  },
];

export const mockUserProfiles: Record<string, UserProfile> = {
  buyer: {
    name: "Ahmed Al-Rashid",
    email: "buyer@example.com",
    phone: "+966 55 123 4567",
    company: {
      en: "Al-Rashid Food Services Co.",
      ar: "شركة الراشد للخدمات الغذائية",
    },
    role: { en: "Procurement Manager", ar: "مدير المشتريات" },
    avatar:
      "https://api.dicebear.com/7.x/initials/svg?seed=AA&backgroundColor=indigo",
    joinedDate: "2024-01-15",
    address: {
      en: "King Fahd Road, Riyadh 12345, Saudi Arabia",
      ar: "طريق الملك فهد، الرياض 12345، المملكة العربية السعودية",
    },
  },
  supplier: {
    name: "Mohammed Al-Qahtani",
    email: "supplier@example.com",
    phone: "+966 50 987 6543",
    company: {
      en: "Al-Madina Dairy & Food Supplies",
      ar: "إمدادات المدينة للألبان والمواد الغذائية",
    },
    role: { en: "Sales Director", ar: "مدير المبيعات" },
    avatar:
      "https://api.dicebear.com/7.x/initials/svg?seed=MQ&backgroundColor=slate",
    joinedDate: "2023-09-01",
    address: {
      en: "Industrial Zone, Dammam 34567, Saudi Arabia",
      ar: "المنطقة الصناعية، الدمام 34567، المملكة العربية السعودية",
    },
  },
  admin: {
    name: "Admin User",
    email: "admin@example.com",
    phone: "+966 54 555 5555",
    company: { en: "Tawreed Platform", ar: "منصة توريد" },
    role: { en: "System Administrator", ar: "مسؤول النظام" },
    avatar:
      "https://api.dicebear.com/7.x/initials/svg?seed=AU&backgroundColor=red",
    joinedDate: "2023-06-01",
    address: {
      en: "Business Bay, Dubai, UAE",
      ar: "الخليج التجاري، دبي، الإمارات العربية المتحدة",
    },
  },
};

export const mockSupplierEntries: SupplierEntry[] = [
  {
    id: "s1",
    companyName: { en: "Al-Madina Dairy & Food Supplies", ar: "إمدادات المدينة للألبان والمواد الغذائية" },
    contactName: "Mohammed Al-Qahtani",
    email: "supplier@example.com",
    phone: "+966 50 987 6543",
    category: "Dairy",
    status: "approved",
    region: "Mansoura",
    joinedDate: "2023-09-01",
    rating: 4.8,
    totalProducts: 45,
    ordersFulfilled: 420,
    activeOrders: 18,
    completionRate: 96,
    acceptanceRate: 97,
    deliverySuccessRate: 95,
    avgFulfillmentDays: 2.3,
    address: { en: "15 Industrial Zone, Mansoura", ar: "15 المنطقة الصناعية، المنصورة" },
    businessLicense: "BL-2023-00421",
    submittedDocuments: ["Commercial Registration", "Tax Certificate", "Product Safety Compliance"],
    activityTimeline: [
      { action: { en: "Updated stock: Milk", ar: "تحديث المخزون: حليب" }, time: "1 day ago" },
      { action: { en: "Accepted Weekly Café Order", ar: "قبول طلب المقهى الأسبوعي" }, time: "2 days ago" },
      { action: { en: "Added Product: Cheese", ar: "إضافة منتج: جبن" }, time: "5 days ago" },
      { action: { en: "Completed Delivery #DEL-001", ar: "إتمام التوصيل DEL-001" }, time: "1 week ago" },
    ],
    products: [
      { name: { en: "Fresh Milk (1L)", ar: "حليب طازج (1 لتر)" }, category: "Dairy", stock: 500, unit: "L" },
      { name: { en: "Cheddar Cheese (1KG)", ar: "جبن شيدر (1 كجم)" }, category: "Dairy", stock: 200, unit: "KG" },
      { name: { en: "Labneh (500g)", ar: "لبنة (500 جم)" }, category: "Dairy", stock: 150, unit: "JAR" },
    ],
  },
  {
    id: "s2",
    companyName: { en: "Arabian Coffee Roasters", ar: "محامص القهوة العربية" },
    contactName: "Khalid Al-Otaibi",
    email: "info@arabiancoffee.sa",
    phone: "+966 55 222 3344",
    category: "Beverages",
    status: "approved",
    region: "Cairo",
    joinedDate: "2024-02-15",
    rating: 4.5,
    totalProducts: 28,
    ordersFulfilled: 210,
    activeOrders: 8,
    completionRate: 94,
    acceptanceRate: 95,
    deliverySuccessRate: 93,
    avgFulfillmentDays: 1.8,
    address: { en: "42 Tahrir Street, Cairo", ar: "42 شارع التحرير، القاهرة" },
    businessLicense: "BL-2024-00112",
    submittedDocuments: ["Commercial Registration", "Tax Certificate", "Health Certificate"],
    activityTimeline: [
      { action: { en: "Added Product: Arabic Coffee Blend", ar: "إضافة منتج: مزيج القهوة العربية" }, time: "3 days ago" },
      { action: { en: "Accepted Resturant Order", ar: "قبول طلب مطعم" }, time: "4 days ago" },
    ],
    products: [
      { name: { en: "Arabic Coffee Premium Blend (1KG)", ar: "قهوة عربية مزيج فاخر (1 كجم)" }, category: "Beverages", stock: 100, unit: "KG" },
      { name: { en: "Green Cardamom (100g)", ar: "هيل أخضر (100 جم)" }, category: "Beverages", stock: 50, unit: "BOX" },
    ],
  },
  {
    id: "s3",
    companyName: { en: "Green Fields Organic Farms", ar: "مزارع الحقول الخضراء العضوية" },
    contactName: "Sara Al-Harbi",
    email: "sara@greenfields.com",
    phone: "+966 56 777 8899",
    category: "Organic",
    status: "pending",
    region: "Alexandria",
    joinedDate: "2024-11-20",
    rating: 0,
    totalProducts: 12,
    ordersFulfilled: 0,
    activeOrders: 0,
    completionRate: 0,
    address: { en: "8 Agricultural Road, Alexandria", ar: "8 طريق الزراعيين، الإسكندرية" },
    submittedDocuments: ["Commercial Registration", "Organic Certification", "Business Plan"],
    activityTimeline: [
      { action: { en: "Submitted application", ar: "تقديم الطلب" }, time: "5 days ago" },
      { action: { en: "Uploaded documents", ar: "رفع المستندات" }, time: "5 days ago" },
    ],
    products: [
      { name: { en: "Organic Tomatoes (1KG)", ar: "طماطم عضوية (1 كجم)" }, category: "Organic", stock: 0, unit: "KG" },
      { name: { en: "Organic Lettuce", ar: "خس عضوي" }, category: "Organic", stock: 0, unit: "UNIT" },
    ],
  },
  {
    id: "s4",
    companyName: { en: "Golden Harvest Dates Co.", ar: "شركة الحصاد الذهبي للتمور" },
    contactName: "Fahad Al-Dosari",
    email: "fahad@goldenharvest.com",
    phone: "+966 53 444 5566",
    category: "Dried Fruits",
    status: "pending",
    region: "Riyadh",
    joinedDate: "2024-12-01",
    rating: 0,
    totalProducts: 8,
    ordersFulfilled: 0,
    activeOrders: 0,
    completionRate: 0,
    address: { en: "22 Date Market, Riyadh", ar: "22 سوق التمور، الرياض" },
    submittedDocuments: ["Commercial Registration", "Product Testing Report"],
    activityTimeline: [
      { action: { en: "Submitted application", ar: "تقديم الطلب" }, time: "2 days ago" },
    ],
    products: [
      { name: { en: "Medjool Dates (1KG)", ar: "تمر مجدول (1 كجم)" }, category: "Dried Fruits", stock: 0, unit: "KG" },
    ],
  },
  {
    id: "s5",
    companyName: { en: "Premium Olive Oil Estates", ar: "مزارع زيت الزيتون الفاخر" },
    contactName: "Nora Al-Shammari",
    email: "nora@oliveoil.sa",
    phone: "+966 58 111 2233",
    category: "Oils",
    status: "approved",
    region: "Jeddah",
    joinedDate: "2024-04-10",
    rating: 4.2,
    totalProducts: 17,
    ordersFulfilled: 180,
    activeOrders: 5,
    completionRate: 98,
    acceptanceRate: 96,
    deliverySuccessRate: 97,
    avgFulfillmentDays: 1.5,
    address: { en: "5 Corniche Road, Jeddah", ar: "5 طريق الكورنيش، جدة" },
    businessLicense: "BL-2024-00345",
    submittedDocuments: ["Commercial Registration", "Tax Certificate", "Export License"],
    activityTimeline: [
      { action: { en: "Completed Delivery #DEL-005", ar: "إتمام التوصيل DEL-005" }, time: "1 day ago" },
      { action: { en: "Accepted Bulk Oil Order", ar: "قبول طلب زيت بالجملة" }, time: "3 days ago" },
    ],
    products: [
      { name: { en: "Extra Virgin Olive Oil (5L)", ar: "زيت زيتون بكر ممتاز (5 لتر)" }, category: "Oils", stock: 80, unit: "TIN" },
      { name: { en: "Organic Olive Oil (1L)", ar: "زيت زيتون عضوي (1 لتر)" }, category: "Oils", stock: 120, unit: "BTL" },
    ],
  },
  {
    id: "s6",
    companyName: { en: "Al-Reef Honey Products", ar: "منتجات الريف للعسل" },
    contactName: "Sultan Al-Ghamdi",
    email: "sultan@alreefhoney.com",
    phone: "+966 57 333 4455",
    category: "Honey",
    status: "rejected",
    region: "Taif",
    joinedDate: "2024-10-05",
    rating: 0,
    totalProducts: 3,
    ordersFulfilled: 0,
    activeOrders: 0,
    completionRate: 0,
    address: { en: "12 Mountain Road, Taif", ar: "12 طريق الجبال، الطائف" },
    submittedDocuments: ["Commercial Registration", "Health Certificate"],
    activityTimeline: [
      { action: { en: "Application rejected - missing certification", ar: "رفض الطلب - الشهادة missing" }, time: "1 month ago" },
    ],
    products: [],
  },
  {
    id: "s7",
    companyName: { en: "Farms Co.", ar: "شركة المزارع" },
    contactName: "Nadia Ali",
    email: "nadia@farms.co",
    phone: "+966 55 111 2222",
    category: "Vegetables",
    status: "suspended",
    region: "Mansoura",
    joinedDate: "2024-06-01",
    rating: 3.2,
    totalProducts: 8,
    ordersFulfilled: 45,
    activeOrders: 0,
    completionRate: 72,
    acceptanceRate: 80,
    deliverySuccessRate: 70,
    avgFulfillmentDays: 4.1,
    address: { en: "3 Farm Road, Mansoura", ar: "3 طريق المزرعة، المنصورة" },
    businessLicense: "BL-2024-00210",
    submittedDocuments: ["Commercial Registration", "Tax Certificate"],
    activityTimeline: [
      { action: { en: "Account suspended - compliance issue", ar: "إيقاف الحساب - مشكلة امتثال" }, time: "2 weeks ago" },
    ],
    products: [
      { name: { en: "Fresh Potatoes (1KG)", ar: "بطاطس طازجة (1 كجم)" }, category: "Vegetables", stock: 300, unit: "KG" },
    ],
  },
  {
    id: "s8",
    companyName: { en: "Cairo Trading Co.", ar: "القاهرة للتجارة" },
    contactName: "Youssef Hany",
    email: "youssef@cairo-trade.com",
    phone: "+966 50 333 4444",
    category: "Bakery",
    status: "suspended",
    region: "Cairo",
    joinedDate: "2024-07-15",
    rating: 2.8,
    totalProducts: 5,
    ordersFulfilled: 22,
    activeOrders: 0,
    completionRate: 65,
    acceptanceRate: 70,
    deliverySuccessRate: 62,
    avgFulfillmentDays: 5.0,
    address: { en: "7 Downtown Ave, Cairo", ar: "7 شارع وسط البلد، القاهرة" },
    businessLicense: "BL-2024-00450",
    submittedDocuments: ["Commercial Registration"],
    activityTimeline: [
      { action: { en: "Account suspended - late deliveries", ar: "إيقاف الحساب - تأخير في التوصيل" }, time: "1 week ago" },
    ],
    products: [
      { name: { en: "Pita Bread (50-pack)", ar: "خبز بيتا (50 حبة)" }, category: "Bakery", stock: 0, unit: "BOX" },
    ],
  },
];

export const mockDeliveries: Delivery[] = [
  {
    id: "d1",
    orderId: "o1",
    orderNumber: "ORD-2024-001",
    address: {
      en: "King Fahd Road, Riyadh 12345, Saudi Arabia",
      ar: "طريق الملك فهد، الرياض 12345، المملكة العربية السعودية",
    },
    status: "delivered",
    estimatedDate: "2024-11-01",
    carrier: "Saudi Express Logistics",
    trackingNumber: "SEL-987654",
  },
  {
    id: "d2",
    orderId: "o2",
    orderNumber: "ORD-2024-002",
    address: {
      en: "Industrial Zone, Dammam 34567, Saudi Arabia",
      ar: "المنطقة الصناعية، الدمام 34567، المملكة العربية السعودية",
    },
    status: "in-transit",
    estimatedDate: "2024-12-05",
    carrier: "Gulf Freight Services",
    trackingNumber: "GFS-456123",
  },
  {
    id: "d3",
    orderId: "o3",
    orderNumber: "ORD-2024-003",
    address: {
      en: "King Fahd Road, Riyadh 12345, Saudi Arabia",
      ar: "طريق الملك فهد، الرياض 12345، المملكة العربية السعودية",
    },
    status: "preparing",
    estimatedDate: "2024-12-20",
    carrier: "Saudi Express Logistics",
    trackingNumber: "SEL-789012",
  },
  {
    id: "d4",
    orderId: "o5",
    orderNumber: "ORD-2024-005",
    address: {
      en: "Business Bay, Dubai, UAE",
      ar: "الخليج التجاري، دبي، الإمارات العربية المتحدة",
    },
    status: "delayed",
    estimatedDate: "2024-12-15",
    carrier: "Gulf Freight Services",
    trackingNumber: "GFS-345678",
  },
];

export const mockCategoryEntries: CategoryEntry[] = [
  {
    id: "c1",
    name: { en: "Dairy", ar: "ألبان" },
    productCount: 85,
    supplierCount: 12,
    active: true,
    monthlyOrders: 1240,
    growth: 18,
    revenue: 320000,
    trend: 'hot',
    supplierBreakdown: { large: 3, medium: 5, small: 4 },
    topProducts: [
      { name: 'Milk', orders: 420 },
      { name: 'Cheese', orders: 300 },
      { name: 'Yogurt', orders: 250 },
      { name: 'Butter', orders: 180 },
    ],
  },
  {
    id: "c2",
    name: { en: "Beverages", ar: "مشروبات" },
    productCount: 60,
    supplierCount: 10,
    active: true,
    monthlyOrders: 980,
    growth: 5,
    revenue: 185000,
    trend: 'stable',
    supplierBreakdown: { large: 2, medium: 4, small: 4 },
    topProducts: [
      { name: 'Arabic Coffee', orders: 380 },
      { name: 'Juices', orders: 220 },
      { name: 'Soft Drinks', orders: 190 },
    ],
  },
  {
    id: "c3",
    name: { en: "Oils", ar: "زيوت" },
    productCount: 35,
    supplierCount: 8,
    active: true,
    monthlyOrders: 560,
    growth: 12,
    revenue: 145000,
    trend: 'growing',
    supplierBreakdown: { large: 2, medium: 3, small: 3 },
    topProducts: [
      { name: 'Olive Oil', orders: 280 },
      { name: 'Vegetable Oil', orders: 160 },
    ],
  },
  {
    id: "c4",
    name: { en: "Grains", ar: "حبوب" },
    productCount: 50,
    supplierCount: 15,
    active: true,
    monthlyOrders: 1100,
    growth: -3,
    revenue: 210000,
    trend: 'declining',
    supplierBreakdown: { large: 4, medium: 6, small: 5 },
    topProducts: [
      { name: 'Basmati Rice', orders: 350 },
      { name: 'Wheat Flour', orders: 280 },
      { name: 'Lentils', orders: 200 },
    ],
  },
  {
    id: "c5",
    name: { en: "Honey", ar: "عسل" },
    productCount: 20,
    supplierCount: 6,
    active: true,
    monthlyOrders: 340,
    growth: 25,
    revenue: 98000,
    trend: 'hot',
    supplierBreakdown: { large: 1, medium: 2, small: 3 },
    topProducts: [
      { name: 'Pure Natural Honey', orders: 180 },
      { name: 'Manuka Honey', orders: 90 },
    ],
  },
  {
    id: "c6",
    name: { en: "Dried Fruits", ar: "فواكه مجففة" },
    productCount: 30,
    supplierCount: 9,
    active: true,
    monthlyOrders: 480,
    growth: 8,
    revenue: 112000,
    trend: 'growing',
    supplierBreakdown: { large: 2, medium: 4, small: 3 },
    topProducts: [
      { name: 'Dates', orders: 260 },
      { name: 'Raisins', orders: 120 },
      { name: 'Dried Apricots', orders: 80 },
    ],
  },
  {
    id: "c7",
    name: { en: "Organic", ar: "عضوي" },
    productCount: 45,
    supplierCount: 11,
    active: true,
    monthlyOrders: 720,
    growth: 22,
    revenue: 195000,
    trend: 'hot',
    supplierBreakdown: { large: 3, medium: 4, small: 4 },
    topProducts: [
      { name: 'Organic Vegetables', orders: 310 },
      { name: 'Organic Fruits', orders: 220 },
      { name: 'Organic Grains', orders: 140 },
    ],
  },
];

export const mockRegionEntries: RegionEntry[] = [
  {
    id: "r1",
    name: { en: "Riyadh", ar: "الرياض" },
    supplierCount: 45,
    buyerCount: 320,
    active: true,
  },
  {
    id: "r2",
    name: { en: "Jeddah", ar: "جدة" },
    supplierCount: 38,
    buyerCount: 280,
    active: true,
  },
  {
    id: "r3",
    name: { en: "Dammam", ar: "الدمام" },
    supplierCount: 25,
    buyerCount: 180,
    active: true,
  },
  {
    id: "r4",
    name: { en: "Mecca", ar: "مكة المكرمة" },
    supplierCount: 18,
    buyerCount: 150,
    active: true,
  },
  {
    id: "r5",
    name: { en: "Medina", ar: "المدينة المنورة" },
    supplierCount: 12,
    buyerCount: 95,
    active: true,
  },
  {
    id: "r6",
    name: { en: "Tabuk", ar: "تبوك" },
    supplierCount: 8,
    buyerCount: 55,
    active: false,
  },
];

export const mockAdminStats: AdminStats = {
  totalUsers: 1280,
  totalSuppliers: 62,
  totalOrders: 340,
  totalRevenue: 2850000,
  pendingSuppliers: 8,
  activeCategories: 7,
  monthlyGrowth: 15.5,
};

export const mockUserEntries: UserEntry[] = [
  {
    id: "u1",
    name: "Omar Fathy",
    email: "omar@omarmarket.com",
    phone: "+966 50 111 2233",
    role: { en: "Buyer", ar: "مشتري" },
    status: "active",
    businessName: { en: "Omar Market", ar: "سوق عمر" },
    region: "Mansoura",
    ordersCreated: 8,
    ordersJoined: 42,
    completedOrders: 38,
    cancelledOrders: 2,
    totalSavings: 12500,
    joinedDate: "2024-01-15",
    lastActive: "2024-12-10",
    activityHistory: [
      { action: { en: "Created Weekly Café Order", ar: "إنشاء طلب المقهى الأسبوعي" }, time: "2 days ago" },
      { action: { en: "Joined Dairy Group Order", ar: "الانضمام لطلب مجموعة الألبان" }, time: "5 days ago" },
      { action: { en: "Cancelled Coffee Order", ar: "إلغاء طلب القهوة" }, time: "1 week ago" },
    ],
  },
  {
    id: "u2",
    name: "Ahmed Ali",
    email: "ahmed@elitecafe.com",
    phone: "+966 55 222 3344",
    role: { en: "Buyer", ar: "مشتري" },
    status: "active",
    businessName: { en: "Elite Café", ar: "مقهى النخبة" },
    region: "Cairo",
    ordersCreated: 15,
    ordersJoined: 25,
    completedOrders: 32,
    cancelledOrders: 1,
    totalSavings: 8750,
    joinedDate: "2023-11-01",
    lastActive: "2024-12-11",
    activityHistory: [
      { action: { en: "Created Monthly Stock Order", ar: "إنشاء طلب المخزون الشهري" }, time: "1 day ago" },
      { action: { en: "Joined Bakery Supplies Order", ar: "الانضمام لطلب مستلزمات المخبز" }, time: "3 days ago" },
    ],
  },
  {
    id: "u3",
    name: "Sara Mohamed",
    email: "sara@groceryplus.com",
    phone: "+966 56 777 8899",
    role: { en: "Buyer", ar: "مشتري" },
    status: "suspended",
    businessName: { en: "Grocery Plus", ar: "بقالة بلس" },
    region: "Alexandria",
    ordersCreated: 3,
    ordersJoined: 8,
    completedOrders: 5,
    cancelledOrders: 4,
    totalSavings: 3200,
    suspensionReason: "Repeated order abuse and payment disputes",
    joinedDate: "2024-06-10",
    lastActive: "2024-11-28",
    activityHistory: [
      { action: { en: "Created Small Grocery Order", ar: "إنشاء طلب بقالة صغير" }, time: "2 weeks ago" },
      { action: { en: "Cancelled Order #ORD-008", ar: "إلغاء الطلب ORD-008" }, time: "3 weeks ago" },
    ],
  },
  {
    id: "u4",
    name: "Mohammed Al-Qahtani",
    email: "supplier@example.com",
    role: { en: "Supplier", ar: "مورد" },
    status: "active",
    joinedDate: "2023-09-01",
    lastActive: "2024-12-11",
  },
  {
    id: "u5",
    name: "Admin User",
    email: "admin@example.com",
    role: { en: "Admin", ar: "مشرف" },
    status: "active",
    joinedDate: "2023-06-01",
    lastActive: "2024-12-11",
  },
  {
    id: "u6",
    name: "Khalid Al-Otaibi",
    email: "khalid@arabiancoffee.sa",
    role: { en: "Supplier", ar: "مورد" },
    status: "active",
    joinedDate: "2024-02-15",
    lastActive: "2024-12-10",
  },
  {
    id: "u7",
    name: "Sara Al-Harbi",
    email: "sara@greenfields.com",
    role: { en: "Supplier", ar: "مورد" },
    status: "active",
    joinedDate: "2024-11-20",
    lastActive: "2024-12-09",
  },
  {
    id: "u8",
    name: "Nora Al-Shammari",
    email: "nora@oliveoil.sa",
    role: { en: "Supplier", ar: "مورد" },
    status: "active",
    joinedDate: "2024-04-10",
    lastActive: "2024-12-08",
  },
  {
    id: "u9",
    name: "Laila Al-Zahrani",
    email: "laila@example.com",
    phone: "+966 54 333 5566",
    role: { en: "Buyer", ar: "مشتري" },
    status: "active",
    businessName: { en: "Laila's Bakery", ar: "مخبز ليلى" },
    region: "Jeddah",
    ordersCreated: 12,
    ordersJoined: 30,
    completedOrders: 28,
    cancelledOrders: 0,
    totalSavings: 18300,
    joinedDate: "2024-03-20",
    lastActive: "2024-12-07",
    activityHistory: [
      { action: { en: "Joined Flour Bulk Order", ar: "الانضمام لطلب الطحين بالجملة" }, time: "1 day ago" },
      { action: { en: "Created Weekly Bakery Order", ar: "إنشاء طلب المخبز الأسبوعي" }, time: "4 days ago" },
    ],
  },
  {
    id: "u10",
    name: "Omar Al-Mutairi",
    email: "omar@example.com",
    phone: "+966 50 444 7788",
    role: { en: "Buyer", ar: "مشتري" },
    status: "suspended",
    businessName: { en: "Desert Rose Restaurant", ar: "مطعم وردة الصحراء" },
    region: "Riyadh",
    ordersCreated: 5,
    ordersJoined: 15,
    completedOrders: 10,
    cancelledOrders: 6,
    totalSavings: 6400,
    suspensionReason: "Multiple late payments on completed orders",
    joinedDate: "2024-05-10",
    lastActive: "2024-12-01",
    activityHistory: [
      { action: { en: "Created Restaurant Supplies Order", ar: "إنشاء طلب مستلزمات المطعم" }, time: "1 week ago" },
      { action: { en: "Cancelled Meat Order", ar: "إلغاء طلب اللحوم" }, time: "2 weeks ago" },
    ],
  },
  {
    id: "u11",
    name: "Hassan Ibrahim",
    email: "hassan@supermarket.com",
    phone: "+966 57 888 9900",
    role: { en: "Buyer", ar: "مشتري" },
    status: "active",
    businessName: { en: "Hassan Supermarket", ar: "سوبر ماركت حسن" },
    region: "Mansoura",
    ordersCreated: 20,
    ordersJoined: 55,
    completedOrders: 50,
    cancelledOrders: 1,
    totalSavings: 22500,
    joinedDate: "2023-08-05",
    lastActive: "2024-12-11",
    activityHistory: [
      { action: { en: "Created Monthly Wholesale Order", ar: "إنشاء طلب الجملة الشهري" }, time: "5 hours ago" },
      { action: { en: "Joined Dairy Products Order", ar: "الانضمام لطلب منتجات الألبان" }, time: "1 day ago" },
    ],
  },
];

export const mockReportEntries: ReportEntry[] = [
  {
    id: "rp1",
    title: { en: "Monthly Revenue Report", ar: "تقرير الإيرادات الشهري" },
    type: { en: "Financial", ar: "مالي" },
    period: "November 2024",
    generatedAt: "2024-12-01",
    total: 450000,
    growth: 12.3,
  },
  {
    id: "rp2",
    title: { en: "Order Volume Report", ar: "تقرير حجم الطلبات" },
    type: { en: "Operations", ar: "عمليات" },
    period: "November 2024",
    generatedAt: "2024-12-01",
    total: 85,
    growth: 8.7,
  },
  {
    id: "rp3",
    title: { en: "New User Registrations", ar: "تسجيلات المستخدمين الجدد" },
    type: { en: "Growth", ar: "نمو" },
    period: "Q4 2024",
    generatedAt: "2024-12-01",
    total: 124,
    growth: 22.5,
  },
  {
    id: "rp4",
    title: { en: "Top Selling Categories", ar: "أفضل التصنيفات مبيعاً" },
    type: { en: "Sales", ar: "مبيعات" },
    period: "2024",
    generatedAt: "2024-12-01",
    total: 8,
    growth: 5.2,
  },
  {
    id: "rp5",
    title: { en: "Supplier Performance Report", ar: "تقرير أداء الموردين" },
    type: { en: "Quality", ar: "جودة" },
    period: "Q4 2024",
    generatedAt: "2024-11-30",
    total: 42,
    growth: -2.1,
  },
  {
    id: "rp6",
    title: { en: "Regional Sales Distribution", ar: "توزيع المبيعات الإقليمي" },
    type: { en: "Geographic", ar: "جغرافي" },
    period: "November 2024",
    generatedAt: "2024-11-30",
    total: 6,
    growth: 10.8,
  },
];

export const mockProductList: SupplierProduct[] = [
  {
    id: "sp1",
    name: { en: "Premium Mixed Cheese Platter", ar: "طبق جبن مشكل فاخر" },
    price: 180,
    stock: 200,
    category: "Dairy",
    status: "active",
    image:
      "https://images.unsplash.com/photo-1552767059-ce1833656d5b?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "sp2",
    name: { en: "Arabic Coffee Premium Blend", ar: "قهوة عربية مزيج فاخر" },
    price: 85,
    stock: 350,
    category: "Beverages",
    status: "active",
    image:
      "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "sp3",
    name: {
      en: "Fresh Full Cream Milk (1L)",
      ar: "حليب طازج كامل الدسم (1 لتر)",
    },
    price: 7.5,
    stock: 1500,
    category: "Dairy",
    status: "active",
    image:
      "https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "sp4",
    name: {
      en: "Extra Virgin Olive Oil (5L)",
      ar: "زيت زيتون بكر ممتاز (5 لتر)",
    },
    price: 145,
    stock: 80,
    category: "Oils",
    status: "active",
    image:
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "sp5",
    name: { en: "Premium Medjool Dates (5kg)", ar: "تمر مجهول فاخر (5 كجم)" },
    price: 220,
    stock: 60,
    category: "Dried Fruits",
    status: "inactive",
    image:
      "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "sp6",
    name: { en: "Pure Natural Honey (3kg)", ar: "عسل طبيعي نقي (3 كجم)" },
    price: 195,
    stock: 40,
    category: "Honey",
    status: "active",
    image:
      "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=800",
  },
];

export const mockGroupOrderDetails: Record<string, GroupOrderDetail> = {
  o1: {
    id: "o1",
    orderNumber: "ORD-2024-001",
    title: { en: "Weekly Café Supplies Order", ar: "طلب مستلزمات المقهى الأسبوعي" },
    createdBy: "Ahmed Café",
    region: "Mansoura",
    createdAt: "June 10",
    deadline: "June 17",
    status: "open",
    participants: [
      { id: "pa1", name: "Ahmed Café", avatar: undefined, joinedAt: "2024-06-10", items: [{ groupOrderItemId: "p1", quantity: 5 }, { groupOrderItemId: "p3", quantity: 20 }] },
      { id: "pa2", name: "Elite Restaurant", avatar: undefined, joinedAt: "2024-06-11", items: [{ groupOrderItemId: "p1", quantity: 8 }, { groupOrderItemId: "p3", quantity: 30 }] },
      { id: "pa3", name: "Omar Market", avatar: undefined, joinedAt: "2024-06-12", items: [{ groupOrderItemId: "p1", quantity: 4 }, { groupOrderItemId: "p3", quantity: 25 }] },
      { id: "pa4", name: "Fresh Store", avatar: undefined, joinedAt: "2024-06-12", items: [{ groupOrderItemId: "p3", quantity: 15 }] },
      { id: "pa5", name: "Café de Paris", avatar: undefined, joinedAt: "2024-06-13", items: [{ groupOrderItemId: "p1", quantity: 3 }] },
      { id: "pa6", name: "Lotus Bakery", avatar: undefined, joinedAt: "2024-06-13", items: [{ groupOrderItemId: "p1", quantity: 6 }, { groupOrderItemId: "p3", quantity: 10 }] },
      { id: "pa7", name: "Green Leaf Restaurant", avatar: undefined, joinedAt: "2024-06-14", items: [{ groupOrderItemId: "p3", quantity: 20 }] },
      { id: "pa8", name: "Saffron Kitchen", avatar: undefined, joinedAt: "2024-06-14", items: [{ groupOrderItemId: "p1", quantity: 2 }, { groupOrderItemId: "p3", quantity: 15 }] },
      { id: "pa9", name: "Al Manar Supermarket", avatar: undefined, joinedAt: "2024-06-15", items: [{ groupOrderItemId: "p1", quantity: 10 }] },
      { id: "pa10", name: "Daily Bread Café", avatar: undefined, joinedAt: "2024-06-15", items: [{ groupOrderItemId: "p3", quantity: 12 }] },
      { id: "pa11", name: "Nile Restaurant", avatar: undefined, joinedAt: "2024-06-15", items: [{ groupOrderItemId: "p1", quantity: 7 }, { groupOrderItemId: "p3", quantity: 18 }] },
      { id: "pa12", name: "Sunrise Diner", avatar: undefined, joinedAt: "2024-06-16", items: [{ groupOrderItemId: "p3", quantity: 8 }] },
    ],
    products: [
      { productId: "p1", productName: { en: "Premium Mixed Cheese Platter", ar: "طبق جبن مشكل فاخر" }, currentQuantity: 45, targetQuantity: 60, unit: "KG", currentPrice: 155, originalPrice: 180, discountAchieved: true, discountPercent: 14 },
      { productId: "p3", productName: { en: "Fresh Full Cream Milk (1L)", ar: "حليب طازج كامل الدسم (1 لتر)" }, currentQuantity: 173, targetQuantity: 250, unit: "L", currentPrice: 6.2, originalPrice: 7.5, discountAchieved: false, discountPercent: 17 },
    ],
    activities: [
      { id: "act1", type: "participant_joined", message: { en: "Elite Restaurant joined", ar: "انضم مطعم النخبة" }, timestamp: "2024-06-11T09:00:00" },
      { id: "act2", type: "participant_joined", message: { en: "Omar Market joined", ar: "انضم سوق عمر" }, timestamp: "2024-06-12T10:30:00" },
      { id: "act3", type: "quantity_updated", message: { en: "Milk quantity increased by 20 L", ar: "تم زيادة كمية الحليب بمقدار 20 لتر" }, timestamp: "2024-06-12T14:00:00" },
      { id: "act4", type: "participant_joined", message: { en: "Fresh Store joined", ar: "انضم المتجر الطازج" }, timestamp: "2024-06-12T16:00:00" },
      { id: "act5", type: "participant_joined", message: { en: "Café de Paris joined", ar: "انضم مقهى باريس" }, timestamp: "2024-06-13T08:00:00" },
      { id: "act6", type: "discount_reached", message: { en: "Cheese reached discount threshold of 50%", ar: "وصل الجبن إلى حد الخصم 50%" }, timestamp: "2024-06-13T11:00:00" },
      { id: "act7", type: "participant_joined", message: { en: "Lotus Bakery joined", ar: "انضم مخبز اللوتس" }, timestamp: "2024-06-13T15:00:00" },
      { id: "act8", type: "supplier_update", message: { en: "Dairy Foods Co. confirmed pricing tier", ar: "أكدت شركة الألبان فئة التسعير" }, timestamp: "2024-06-14T09:00:00" },
      { id: "act9", type: "participant_joined", message: { en: "Green Leaf Restaurant joined", ar: "انضم مطعم الورقة الخضراء" }, timestamp: "2024-06-14T11:00:00" },
      { id: "act10", type: "participant_joined", message: { en: "Saffron Kitchen joined", ar: "انضم مطبخ الزعفران" }, timestamp: "2024-06-14T14:00:00" },
      { id: "act11", type: "participant_joined", message: { en: "Al Manar Supermarket joined", ar: "انضم سوق المنار" }, timestamp: "2024-06-15T09:00:00" },
      { id: "act12", type: "participant_joined", message: { en: "Daily Bread Café joined", ar: "انضم مقهى الخبز اليومي" }, timestamp: "2024-06-15T11:00:00" },
      { id: "act13", type: "participant_joined", message: { en: "Nile Restaurant joined", ar: "انضم مطعم النيل" }, timestamp: "2024-06-15T14:00:00" },
      { id: "act14", type: "participant_joined", message: { en: "Sunrise Diner joined", ar: "انضم مطعم صن رايز" }, timestamp: "2024-06-16T10:00:00" },
    ],
    totalOrderValue: 22000,
    currentDiscount: 3500,
    projectedFinalCost: 18500,
    supplier: { name: "Dairy Foods Co.", deliveryRegion: "Mansoura", expectedDelivery: "June 20 - June 22" },
  },
  o2: {
    id: "o2",
    orderNumber: "ORD-2024-002",
    title: { en: "Premium Dry Fruits & Honey Bulk", ar: "طلبية فواكه مجففة وعسل بالجملة" },
    createdBy: "Ahmed Café",
    region: "Mansoura",
    createdAt: "November 20",
    deadline: "December 5",
    status: "delivered",
    participants: [
      { id: "pb1", name: "Ahmed Café", joinedAt: "2024-11-20", items: [{ groupOrderItemId: "p5", quantity: 8 }, { groupOrderItemId: "p6", quantity: 5 }] },
      { id: "pb2", name: "Elite Restaurant", joinedAt: "2024-11-21", items: [{ groupOrderItemId: "p5", quantity: 6 }] },
      { id: "pb3", name: "Omar Market", joinedAt: "2024-11-22", items: [{ groupOrderItemId: "p5", quantity: 10 }, { groupOrderItemId: "p6", quantity: 4 }] },
      { id: "pb4", name: "Fresh Store", joinedAt: "2024-11-23", items: [{ groupOrderItemId: "p5", quantity: 3 }, { groupOrderItemId: "p6", quantity: 3 }] },
      { id: "pb5", name: "Dates Lover Shop", joinedAt: "2024-11-24", items: [{ groupOrderItemId: "p5", quantity: 3 }] },
    ],
    products: [
      { productId: "p5", productName: { en: "Premium Medjool Dates (5kg)", ar: "تمر مجهول فاخر (5 كجم)" }, currentQuantity: 30, targetQuantity: 30, unit: "BOX", currentPrice: 187, originalPrice: 220, discountAchieved: true, discountPercent: 15 },
      { productId: "p6", productName: { en: "Pure Natural Honey (3kg)", ar: "عسل طبيعي نقي (3 كجم)" }, currentQuantity: 12, targetQuantity: 20, unit: "JAR", currentPrice: 175, originalPrice: 195, discountAchieved: true, discountPercent: 10 },
    ],
    activities: [
      { id: "act15", type: "participant_joined", message: { en: "Elite Restaurant joined", ar: "انضم مطعم النخبة" }, timestamp: "2024-11-21" },
      { id: "act16", type: "participant_joined", message: { en: "Omar Market joined", ar: "انضم سوق عمر" }, timestamp: "2024-11-22" },
      { id: "act17", type: "discount_reached", message: { en: "Dates reached discount threshold", ar: "وصل التمر إلى حد الخصم" }, timestamp: "2024-11-23" },
      { id: "act18", type: "participant_joined", message: { en: "Fresh Store joined", ar: "انضم المتجر الطازج" }, timestamp: "2024-11-23" },
      { id: "act19", type: "participant_joined", message: { en: "Dates Lover Shop joined", ar: "انضم متجر عشاق التمر" }, timestamp: "2024-11-24" },
      { id: "act20", type: "supplier_update", message: { en: "Supplier confirmed delivery date", ar: "أكد المورد تاريخ التسليم" }, timestamp: "2024-11-28" },
    ],
    totalOrderValue: 12000,
    currentDiscount: 1500,
    projectedFinalCost: 10500,
    supplier: { name: "Golden Harvest Dates Co.", deliveryRegion: "Mansoura", expectedDelivery: "December 3 - December 5" },
  },
  o3: {
    id: "o3",
    orderNumber: "ORD-2024-003",
    title: { en: "Beverages & Grains Collective Order", ar: "طلبية مشروبات وحبوب جماعية" },
    createdBy: "Ahmed Café",
    region: "Riyadh",
    createdAt: "December 1",
    deadline: "December 20",
    status: "supplier_confirmed",
    participants: [
      { id: "pc1", name: "Ahmed Café", joinedAt: "2024-12-01", items: [{ groupOrderItemId: "p2", quantity: 20 }, { groupOrderItemId: "p7", quantity: 4 }] },
      { id: "pc2", name: "Café Vienna", joinedAt: "2024-12-02", items: [{ groupOrderItemId: "p2", quantity: 15 }] },
      { id: "pc3", name: "Rice House Restaurant", joinedAt: "2024-12-03", items: [{ groupOrderItemId: "p7", quantity: 6 }] },
      { id: "pc4", name: "Tea Time Café", joinedAt: "2024-12-05", items: [{ groupOrderItemId: "p2", quantity: 10 }] },
      { id: "pc5", name: "Spice Garden", joinedAt: "2024-12-06", items: [{ groupOrderItemId: "p7", quantity: 3 }] },
    ],
    products: [
      { productId: "p2", productName: { en: "Arabic Coffee - Premium Blend", ar: "قهوة عربية - مزيج فاخر" }, currentQuantity: 45, targetQuantity: 60, unit: "KG", currentPrice: 72, originalPrice: 85, discountAchieved: true, discountPercent: 15 },
      { productId: "p7", productName: { en: "Premium Basmati Rice (25kg)", ar: "أرز بسمتي فاخر (25 كجم)" }, currentQuantity: 13, targetQuantity: 20, unit: "BAG", currentPrice: 145, originalPrice: 165, discountAchieved: false, discountPercent: 12 },
    ],
    activities: [
      { id: "act21", type: "participant_joined", message: { en: "Café Vienna joined", ar: "انضم مقهى فيينا" }, timestamp: "2024-12-02" },
      { id: "act22", type: "participant_joined", message: { en: "Rice House Restaurant joined", ar: "انضم مطعم بيت الأرز" }, timestamp: "2024-12-03" },
      { id: "act23", type: "participant_joined", message: { en: "Tea Time Café joined", ar: "انضم مقهى تايم تاي" }, timestamp: "2024-12-05" },
      { id: "act24", type: "discount_reached", message: { en: "Coffee reached discount threshold", ar: "وصلت القهوة إلى حد الخصم" }, timestamp: "2024-12-05" },
      { id: "act25", type: "participant_joined", message: { en: "Spice Garden joined", ar: "انضم مطعم سبايس جاردن" }, timestamp: "2024-12-06" },
      { id: "act26", type: "supplier_update", message: { en: "Arabian Coffee Roasters confirmed bulk pricing", ar: "أكدت محامص القهوة العربية التسعير بالجملة" }, timestamp: "2024-12-08" },
    ],
    totalOrderValue: 7200,
    currentDiscount: 875,
    projectedFinalCost: 6325,
    supplier: { name: "Arabian Coffee Roasters", deliveryRegion: "Riyadh", expectedDelivery: "December 18 - December 20" },
  },
  o4: {
    id: "o4",
    orderNumber: "ORD-2024-004",
    title: { en: "Olive Oil Bulk Purchase", ar: "شراء زيت زيتون بالجملة" },
    createdBy: "Ahmed Café",
    region: "Riyadh",
    createdAt: "December 10",
    deadline: "December 28",
    status: "closing_soon",
    participants: [
      { id: "pd1", name: "Ahmed Café", joinedAt: "2024-12-10", items: [{ groupOrderItemId: "p4", quantity: 10 }] },
      { id: "pd2", name: "Mediterranean Grill", joinedAt: "2024-12-11", items: [{ groupOrderItemId: "p4", quantity: 8 }] },
      { id: "pd3", name: "Salads & More", joinedAt: "2024-12-13", items: [{ groupOrderItemId: "p4", quantity: 5 }] },
      { id: "pd4", name: "Healthy Bites Café", joinedAt: "2024-12-14", items: [{ groupOrderItemId: "p4", quantity: 2 }] },
    ],
    products: [
      { productId: "p4", productName: { en: "Extra Virgin Olive Oil (5L)", ar: "زيت زيتون بكر ممتاز (5 لتر)" }, currentQuantity: 25, targetQuantity: 40, unit: "TIN", currentPrice: 123, originalPrice: 145, discountAchieved: false, discountPercent: 15 },
    ],
    activities: [
      { id: "act27", type: "participant_joined", message: { en: "Mediterranean Grill joined", ar: "انضم مطعم ميديتيرينيان جريل" }, timestamp: "2024-12-11" },
      { id: "act28", type: "participant_joined", message: { en: "Salads & More joined", ar: "انضم سلطات آند مور" }, timestamp: "2024-12-13" },
      { id: "act29", type: "participant_joined", message: { en: "Healthy Bites Café joined", ar: "انضم مقهى هيلثي بايتس" }, timestamp: "2024-12-14" },
      { id: "act30", type: "quantity_updated", message: { en: "Olive oil quantity increased by 5 tins", ar: "تم زيادة كمية زيت الزيتون بمقدار 5 علب" }, timestamp: "2024-12-14" },
    ],
    totalOrderValue: 3625,
    currentDiscount: 0,
    projectedFinalCost: 3625,
    supplier: { name: "Premium Olive Oil Estates", deliveryRegion: "Riyadh", expectedDelivery: "December 26 - December 28" },
  },
  o5: {
    id: "o5",
    orderNumber: "ORD-2024-005",
    title: { en: "Water Supply Bulk Order", ar: "طلبية مياه بالجملة" },
    createdBy: "Ahmed Café",
    region: "Dubai",
    createdAt: "November 5",
    deadline: "December 15",
    status: "delivered",
    participants: [
      { id: "pe1", name: "Ahmed Café", joinedAt: "2024-11-05", items: [{ groupOrderItemId: "p8", quantity: 50 }] },
      { id: "pe2", name: "Oasis Hotel", joinedAt: "2024-11-06", items: [{ groupOrderItemId: "p8", quantity: 80 }] },
      { id: "pe3", name: "Desert Palm Resort", joinedAt: "2024-11-07", items: [{ groupOrderItemId: "p8", quantity: 40 }] },
      { id: "pe4", name: "Crystal Tower Café", joinedAt: "2024-11-08", items: [{ groupOrderItemId: "p8", quantity: 30 }] },
    ],
    products: [
      { productId: "p8", productName: { en: "Natural Mineral Water (1.5L x 12)", ar: "مياه معدنية طبيعية (1.5 لتر × 12)" }, currentQuantity: 200, targetQuantity: 200, unit: "CASE", currentPrice: 20, originalPrice: 24, discountAchieved: true, discountPercent: 17 },
    ],
    activities: [
      { id: "act31", type: "participant_joined", message: { en: "Oasis Hotel joined", ar: "انضم فندق الواحة" }, timestamp: "2024-11-06" },
      { id: "act32", type: "participant_joined", message: { en: "Desert Palm Resort joined", ar: "انضم منتجع ديزرت بالم" }, timestamp: "2024-11-07" },
      { id: "act33", type: "participant_joined", message: { en: "Crystal Tower Café joined", ar: "انضم مقهى كريستال تاور" }, timestamp: "2024-11-08" },
      { id: "act34", type: "discount_reached", message: { en: "Water reached discount threshold", ar: "وصلت المياه إلى حد الخصم" }, timestamp: "2024-11-10" },
      { id: "act35", type: "supplier_update", message: { en: "Supplier confirmed delivery", ar: "أكد المورد التسليم" }, timestamp: "2024-11-25" },
    ],
    totalOrderValue: 4800,
    currentDiscount: 800,
    projectedFinalCost: 4000,
    supplier: { name: "Pure Springs Water Co.", deliveryRegion: "Dubai", expectedDelivery: "December 13 - December 15" },
  },
};

export const mockDrafts: SavedOrderDraft[] = [
  {
    id: "draft1",
    name: "Weekly Café Supplies",
    description: "Shared order for dairy products, coffee, and sugar.",
    region: "Mansoura",
    deadlineDate: "2026-06-20",
    deadlineTime: "18:00",
    items: [
      { productId: "p3", name: "Fresh Full Cream Milk (1L)", category: "Dairy", quantity: 60, price: 7.5, unit: "L", stock: 1500 },
      { productId: "p2", name: "Arabic Coffee - Premium Blend", category: "Beverages", quantity: 20, price: 85, unit: "KG", stock: 350 },
      { productId: "p7", name: "Premium Basmati Rice (25kg)", category: "Grains", quantity: 10, price: 165, unit: "BAG", stock: 300 },
    ],
    totalCost: 3600,
    totalQuantity: 90,
    savedAt: "2026-06-15T10:30:00",
    type: "draft",
  },
  {
    id: "draft2",
    name: "Olive Oil Bulk Purchase",
    description: "",
    region: "Riyadh",
    deadlineDate: "2026-06-28",
    deadlineTime: "12:00",
    items: [
      { productId: "p4", name: "Extra Virgin Olive Oil (5L)", category: "Oils", quantity: 25, price: 145, unit: "TIN", stock: 80 },
    ],
    totalCost: 3625,
    totalQuantity: 25,
    savedAt: "2026-06-14T14:00:00",
    type: "draft",
  },
  {
    id: "draft3",
    name: "Honey & Dates Bundle",
    description: "Monthly sweet supplies",
    region: "Jeddah",
    deadlineDate: "2026-07-05",
    deadlineTime: "16:00",
    items: [
      { productId: "p6", name: "Pure Natural Honey (3kg)", category: "Honey", quantity: 8, price: 195, unit: "JAR", stock: 40 },
      { productId: "p5", name: "Premium Medjool Dates (5kg)", category: "Dried Fruits", quantity: 12, price: 220, unit: "BOX", stock: 60 },
    ],
    totalCost: 4200,
    totalQuantity: 20,
    savedAt: "2026-06-13T09:00:00",
    type: "draft",
  },
];

export const mockSavedTemplates: SavedOrderDraft[] = [
  {
    id: "tmpl1",
    name: "Monthly Dairy Order",
    description: "Regular monthly dairy supplies for the café.",
    region: "Mansoura",
    deadlineDate: "",
    deadlineTime: "",
    items: [
      { productId: "p3", name: "Fresh Full Cream Milk (1L)", category: "Dairy", quantity: 100, price: 7.5, unit: "L", stock: 1500 },
      { productId: "p1", name: "Premium Mixed Cheese Platter", category: "Dairy", quantity: 15, price: 180, unit: "KG", stock: 200 },
    ],
    totalCost: 3450,
    totalQuantity: 115,
    savedAt: "2026-06-01T08:00:00",
    type: "template",
  },
  {
    id: "tmpl2",
    name: "Ramadan Bulk Supplies",
    description: "Special Ramadan order with dates, honey, and beverages.",
    region: "Cairo",
    deadlineDate: "",
    deadlineTime: "",
    items: [
      { productId: "p5", name: "Premium Medjool Dates (5kg)", category: "Dried Fruits", quantity: 30, price: 220, unit: "BOX", stock: 60 },
      { productId: "p6", name: "Pure Natural Honey (3kg)", category: "Honey", quantity: 20, price: 195, unit: "JAR", stock: 40 },
      { productId: "p2", name: "Arabic Coffee - Premium Blend", category: "Beverages", quantity: 25, price: 85, unit: "KG", stock: 350 },
      { productId: "p8", name: "Natural Mineral Water (1.5L x 12)", category: "Beverages", quantity: 50, price: 24, unit: "CASE", stock: 800 },
    ],
    totalCost: 14075,
    totalQuantity: 125,
    savedAt: "2026-05-20T10:00:00",
    type: "template",
  },
  {
    id: "tmpl3",
    name: "Weekly Bakery Essentials",
    description: "Flour, oil, and sugar for the bakery.",
    region: "Alexandria",
    deadlineDate: "",
    deadlineTime: "",
    items: [
      { productId: "p7", name: "Premium Basmati Rice (25kg)", category: "Grains", quantity: 5, price: 165, unit: "BAG", stock: 300 },
      { productId: "p4", name: "Extra Virgin Olive Oil (5L)", category: "Oils", quantity: 10, price: 145, unit: "TIN", stock: 80 },
    ],
    totalCost: 2275,
    totalQuantity: 15,
    savedAt: "2026-05-15T07:30:00",
    type: "template",
  },
];

export const totalSavings = 12450;

export const mockNearbyOrders = [
  {
    id: "no1",
    host: { en: "Al-Rashid Food Services", ar: "خدمات الراشد الغذائية" },
    product: { en: "Premium Arabic Coffee - 50kg Bulk", ar: "قهوة عربية فاخرة - 50 كجم بالجملة" },
    quantity: 50,
    unitPrice: 72.25,
    minJoin: 5,
    currentParticipants: 8,
    maxParticipants: 15,
    deadline: "2024-12-20",
    distance: "1.2 km",
    savings: 15,
  },
  {
    id: "no2",
    host: { en: "Madina Dairy Co.", ar: "شركة ألبان المدينة" },
    product: { en: "Fresh Milk (1L) - 200 units", ar: "حليب طازج (1 لتر) - 200 وحدة" },
    quantity: 200,
    unitPrice: 6.20,
    minJoin: 10,
    currentParticipants: 12,
    maxParticipants: 25,
    deadline: "2024-12-18",
    distance: "2.5 km",
    savings: 18,
  },
  {
    id: "no3",
    host: { en: "Golden Harvest Dates", ar: "الحصاد الذهبي للتمور" },
    product: { en: "Medjool Dates (5kg) - 30 boxes", ar: "تمر مجهول (5 كجم) - 30 صندوق" },
    quantity: 30,
    unitPrice: 187,
    minJoin: 3,
    currentParticipants: 5,
    maxParticipants: 10,
    deadline: "2024-12-22",
    distance: "3.8 km",
    savings: 12,
  },
  {
    id: "no4",
    host: { en: "Premium Olive Estates", ar: "مزارع الزيتون الفاخر" },
    product: { en: "Extra Virgin Olive Oil (5L) - 40 tins", ar: "زيت زيتون بكر ممتاز (5 لتر) - 40 علبة" },
    quantity: 40,
    unitPrice: 123.25,
    minJoin: 4,
    currentParticipants: 6,
    maxParticipants: 12,
    deadline: "2024-12-25",
    distance: "0.8 km",
    savings: 20,
  },
];

export const mockSystemAlerts = [
  { id: 'a1', type: 'warning', message: { en: 'Supplier "Green Fields Organic" pending approval for 5 days', ar: 'المورد "الحقول الخضراء" في انتظار الموافقة لمدة 5 أيام' }, time: '2 hours ago' },
  { id: 'a2', type: 'info', message: { en: '12 new buyer registrations today', ar: '12 تسجيل مشتري جديد اليوم' }, time: '4 hours ago' },
  { id: 'a3', type: 'error', message: { en: 'Delivery #DEL-003 is delayed by 2 days', ar: 'التوصيل رقم DEL-003 متأخر بيومين' }, time: '1 day ago' },
  { id: 'a4', type: 'info', message: { en: 'Monthly revenue target at 78%', ar: 'هدف الإيرادات الشهرية عند 78%' }, time: '1 day ago' },
];
